spring:
  application:
    name: 3040
  datasource:
    url: jdbc:postgresql://localhost:5432/3040
    username: root
    password: beyondeyesight
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
